### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by Nik1990** [helfi92/material-ui-treeview#1]
Hi, how can i change background color of selected child element?

Thanks

**Comment by helfi92** [comment]
_Example: Changing the background color of a selected list item to red_

```jsx
const styles = theme => ({
  selected: {
    '&:focus': {
      backgroundColor: 'red',
    },
  },
});

// ...

<MuiTreeView listItemProps={{ className: classes.selected }} />

// ...
```

**Comment by Nik1990** [comment]
Mmm seems not work. There is the code

`import React, { Component } from "react";
import MuiTreeView from 'material-ui-treeview';
import {connect} from "react-redux";
import {selectedTreeElement} from '../../actions/tree/treeActions'
import Button from '@material-ui/core/Button';

const tree = [
    {
        value: 'Parent A',
        nodes: [{ value: 'Child A' }, { value: 'Child B' }],
    },
    {
        value: 'Parent B',
        nodes: [
            {
                value: 'Child C',
            },
            {
                value: 'Parent C',
                nodes: [
                    { value: 'Child D' },
                    { value: 'Child E' },
                    { value: 'Child F' },

                ],
            },
        ],
    },
];


class TreeVieWrapper extends Component {

    constructor(props) {
        super(props);
        this.onNodeSelect = this.onNodeSelect.bind(this);
    }

    onNodeSelect(node) {
        this.props.selectedTreeElement({nodeName: node});
    }


  render() {

      const styles = () => ({
          selected: {
              '&:focus': {
                  backgroundColor: 'red',
              },
          },
      });

    return (
        <div style={{margin: '10px', overflowY: 'auto', maxHeight: '300px'}}>
        <MuiTreeView listItemProps={{ className: styles.selected }}
                     onLeafClick={node => this.onNodeSelect(node)}
                     tree={tree} />

            <Button onClick={this.toggleDockSize} variant="fab" color="primary" aria-label="add">
                </Button>
        </div>


  );
  }
}


const mapDispatchToProps = (dispatch) => {
    return {
        selectedTreeElement: (elem) => dispatch(selectedTreeElement(elem))
    };
};

export default connect(null, mapDispatchToProps)(TreeVieWrapper);
`

Any ideas?

Thanks

**Comment by helfi92** [comment]
To inject custom styling with material-ui, you can use `withStyles`:

```jsx
// ...
import { withStyles } from '@material-ui/core/styles';

const styles = () => ({
  selected: {
    '&:focus': {
      backgroundColor: 'red',
    },
  },
});

// ...

export default compose(
  withStyles(styles),
  connect(null, mapDispatchToProps),
)(TreeVieWrapper);
```

For more information about inject styling with material-ui, refer to https://material-ui.com/customization/overrides/#1-specific-variation-for-a-one-time-situation. Let me know if that helps.

**Comment by Nik1990** [comment]
Mmm i tried with your suggest but not work. I had imported 'compose' from:
import compose from 'recompose/compose';
It's correct?

Thanks

**Comment by helfi92** [comment]
Your import statement looks good to me. Here's a live example (not using redux) you can see it working: https://codesandbox.io/s/w4r6zxyjl.

**Comment by Nik1990** [comment]
Ook. Now it works. I forget to add 'classes' refs.
Thanks
