### ISSUE TITLE
Node ID

### ISSUE THREAD

**Issue by svenschaefer** [helfi92/material-ui-treeview#10]
Beside the node value it would be useful to use a node ID, too, because the text value can be ambiguous, in case that the same text is the child value at different parents.

**Comment by helfi92** [comment]
@svenschaefer Good idea! Let me know if you're interested in sending a PR.

**Comment by fanick-ber** [comment]
I hope the PR #25 goes in the direction of this idea?

**Comment by helfi92** [comment]
Thank you for the pull request. I'll take a look soon :)

**Comment by helfi92** [comment]
Published in `v3.0.2`. This is a breaking change: The `onLeafClick` function now returns an object instead of a value.
