### ISSUE TITLE
Custom getter for attribututes

### ISSUE THREAD

**Issue by franklinyu** [helfi92/material-ui-treeview#22]
This is a feature request.

I already have a recursive data-structure from some other library like this:

```json
{
  "name": "foo",
  "children": [{
    "name": "bar"
  }]
}
```

Currently I recursively convert it into

```json
{
  "value": "foo",
  "nodes": [{
    "value": "bar"
  }]
}
```

but if the data-structure gets big, I want to do this lazily (only convert the part that user expand).

I imaging the API to be like this:

```jsx
const tree = {
  name: 'foo',
  children: [{
    name: 'bar',
  }],
};
return (
  <MuiTreeView
    tree={tree}
    getValue={tree => tree.name}
    getNodes={tree => tree.children}
  />
);
```

**Comment by helfi92** [comment]
How big is your data structure? I don't think you would lose a lot of performance by looping over your data structure and renaming keys as long as you just do it once and make sure your application doesn't do it again.

**Comment by franklinyu** [comment]
I think it’s like 100k nodes? I would re-open if benchmark shows that it takes long.
