### ISSUE TITLE
Closing expanded panel on click of another

### ISSUE THREAD

**Issue by jodays** [helfi92/material-ui-treeview#23]
I'm trying to close expansion panel

**Comment by helfi92** [comment]
> I'm trying to close expansion panel on click of another expansion panel.

I'm not sure I understand what you mean. Could you elaborate, please?

**Comment by jodays** [comment]
So with your library it builds a sidenav using a tree that is an array of objects. Each object has a value which creates the main sidenav headings. Within those are nested nodes. On click of one of the main sidenav headings, the expansion panel you are using from material UI expands. My issue is that they all stay open even if you click on another expansion panel. I want the main headings to collapse on click of another.

**Comment by jodays** [comment]
I only see expansionPanelSummary and expansionPanelDetails. How can I target the expansion panel itself and override some of its behaviour?

**Comment by helfi92** [comment]
To do what you are asking requires the consumer to handle the state of the tree. We could add another prop `collapsed` to each node. If you are interested in implementing it, feel free to create a pull-request. I will be happy to accept this feature.

**Comment by jodays** [comment]
I've forked your repo and I'm trying to point my package json to my fork and it keeps failing. I'm just trying to work on it within my project before I do a pull request. . I suspect it has something to do with the gitignore and the build. This is my first time doing something like this, any direction?

**Comment by jodays** [comment]
@helfi92 Hi Helfi so I'm doing this to close expansion panels when another is clicked
  handlePanelChange = panel => (event, expanded,parent ) => {

    ```
 this.setState({
      expanded: expanded ? panel : false, 
    });
 
  };
```
And in the component I have
```
 <ExpansionPanel
      expanded={expanded === node.value } onChange={this.handlePanelChange(node.value)} >
```
This works for when another parent expansion panel is clicked. It closes the other; however, this doesn't allow me to open the nested expansion panel. So if I open an expansion panel and then try to click on child nested expansion panel, it wont open. I guess because it's trying to close the expansion panel. Have any direction on how I can keep the expansion panel open if a child expansion panel within the parent is clicked. but close it if another parent expansion panel is clicked.
