### ISSUE TITLE
Issues with development and contribution

### ISSUE THREAD

**Issue by fanick-ber** [helfi92/material-ui-treeview#24]
Hi,
I wanted to test some things. I faced trouble to get the clone up and running:

I get an error trying to develop (`yarn start`): 
```
StyleGuide.js:1 Uncaught Error: Cannot find module "rsg-components/StyleGuide/StyleGuideRenderer"
    at Object.<anonymous> (StyleGuide.js:1)
    at __webpack_require__ (bootstrap 43c144344700865d31c9:707)
    at fn (bootstrap 43c144344700865d31c9:112)
    at Object.<anonymous> (index.js:1)
    at __webpack_require__ (bootstrap 43c144344700865d31c9:707)
    at fn (bootstrap 43c144344700865d31c9:112)
    at Object.<anonymous> (renderStyleguide.js:1)
    at __webpack_require__ (bootstrap 43c144344700865d31c9:707)
    at fn (bootstrap 43c144344700865d31c9:112)
    at Object.<anonymous> (index.js:1)
 ```

The errors goes away when I uncomment line 29 and 30 in the `.neutrinorc.js`: https://github.com/helfi92/material-ui-treeview/blob/0a38ef687933c314bdd7a2fdd8ff52b66507ba68/.neutrinorc.js#L29-L30
The styling is missing then.
I have no experience with styleguidist or neutrino, maybe I missed to install something?

Thanks in advance!

**Edit:** I would be happy about some comments, how to use this project with neutrino and styleguide. Is there any chance to start a development server for the `src/index.jsx` ?

**Comment by fanick-ber** [comment]
Thanks for your quick answer!

I think I already tried similar things before. The fresh reinstall does not change anything:
```
➜  material-ui-treeview git:(highlightItem) ✗ rm -rf node_modules/ && yarn install
yarn install v1.12.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "neutrino-middleware-styleguidist > react-styleguidist > html-webpack-plugin@2.30.1" has unmet peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3".
warning "neutrino-middleware-styleguidist > react-styleguidist > uglifyjs-webpack-plugin@1.2.4" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "neutrino-middleware-styleguidist > react-styleguidist > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "neutrino-middleware-styleguidist > react-styleguidist > style-loader > schema-utils@0.4.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "neutrino-preset-mozilla-frontend-infra > eslint-config-prettier@2.9.0" has unmet peer dependency "eslint@>=3.14.1".
warning "neutrino-preset-mozilla-frontend-infra > @neutrinojs/airbnb > @neutrinojs/eslint > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
[4/4] Building fresh packages...
Done in 285.77s.
➜  material-ui-treeview git:(highlightItem) ✗ yarn start
yarn run v1.12.1
$ neutrino styleguide:start
✔ Styleguidist server running at http://0.0.0.0:6060
```
Going to localhost:6060 (the readme says port 5000) gives again the same error `Uncaught Error: Cannot find module "rsg-components/StyleGuide/StyleGuideRenderer"`
I use an ubuntu subsystem on Windows 10. Unfortunately I don't understand, how the combination of neutrino and styleguide should work. There is no `StyleGuideRenderer.jsx` at all.

I do find a `StyleGuideRenderer.js` in `node_modules/react-styleguidist/lib/rsg-components/StyleGuide`, however, it still gives (beside the file ending) the same error, if I change the `jsx` to `js` in the `.neutrinorc.js`

**Comment by helfi92** [comment]
Wow, I was able to replicate on a fresh clone of the project. It turns out I had `styleguide` listed in the `.gitignore` folder which prevented me from pushing `src/styleguide` to version control. The gitignore should be `/styleguide` so that the styleguide directory inside `src` is pushed. I'll have that fixed now.

**Comment by helfi92** [comment]
Pull the latest changes from master and try again. It should work now :)

**Comment by helfi92** [comment]
Apologies for the trouble.
