### ISSUE TITLE
Add/Delete functionality

### ISSUE THREAD

**Issue by NAisaac** [helfi92/material-ui-treeview#3]
First off, thank you for creating this. It's simple and intuitive! I'm wanting to extend it with add/delete node functionality; do you have any recommendation?

**Comment by helfi92** [comment]
Hi @NAisaac. I'm glad you're enjoying the library :) To add/delete nodes, I recommend simply modifying the array given to the `tree` prop.

```jsx
handleLeafClick = () => {
  this.setState({
    tree: this.state.tree.concat({
      value: 'Parent D',
      nodes: [{ value: 'Child G' }, { value: 'Child H' }],
    })
  })
}


render() {
  return <MuiTreeView onLeafClick={this.handleLeafClick} tree={this.state.tree} />'
}
```

**Comment by NAisaac** [comment]
So get the node's value through _onLeafClick_ function, then traverse the n-ary tree by value to perform add/delete, and finally setState tree?

**Comment by helfi92** [comment]
Not necessarily. All you have to do is provide `MuiTreeView` with the new tree and the component will re-render.

**Comment by helfi92** [comment]
_Another example:_

```jsx
handleTreeChange = () => {
  const newTree = [{ value: 'Parent A' }]; 

  this.setState({ tree: newTree });
}

render() {
  return (
    <div>
      <button onClick={this.handleTreeChange}>Click me</button>
      <MuiTreeView tree={this.state.tree} />'
    </div>
  )
}
```

**Comment by NAisaac** [comment]
I was thinking an add/delete icon on each node 🤔Which would need some kind of tree traversal in order to create the newTree, no?

**Comment by helfi92** [comment]
Ah, if you want the addition/deletion to happen after a user clicks on a leaf node, then you can definitely get the node's value through onLeafClick and then traverse the tree by value to perform the addition/deletion. Setting the state with the new tree will then update the view.
