### ISSUE TITLE
Integrated with react router

### ISSUE THREAD

**Issue by birendra-90** [helfi92/material-ui-treeview#33]
How do i integrate react router

**Comment by helfi92** [comment]
By providing an `href` key to a leaf element in the tree `material-ui-treeview` will use the `Link` component of `react-router-dom` to perform the transition.

```jsx
const tree = [
  {
    value: 'Parent A',
    nodes: [{ value: 'Child A', href: '/child-a' }, { value: 'Child B', href: '/child-b' }],
  },
];

// ...

<MuiTreeView tree={tree} />
```

**Comment by birendra-90** [comment]
@helfi92 Thank you so much

**Comment by helfi92** [comment]
You're welcome!
