### ISSUE TITLE
onLeafClick() not getting a node's all properties

### ISSUE THREAD

**Issue by farshidbakh** [helfi92/material-ui-treeview#34]
I build my tree with series of node and for each node I set the following fields:

                    value: argTree.subtreeNodes[i].name,
                        id: argTree.subtreeNodes[i].id,
                        data: argTree.subtreeNodes[i].name,
                        type: argTree.subtreeNodes[i].name,
                        entity: argTree.subtreeNodes[i].entityId,

if I use the  onLeafClick() , I only get the "value" and "id" (see above) , and not other field. I  intentionally assigned "data' to "name" to make sure that name exists.  

 onNodeSelect(node) {

        var noed  = node;
        var i=0;
        i=i+1;
        alert("the node type is " + node.value); //if I change the node.value to node.type, I get undefined, even though they are assigned to the same variable.
    }
    render() {
        var tempTree =this.convertSubTreetoTableTree(this.props.locationSubtreeResp);

        return (
            < MuiTreeView tree = {tempTree}   onLeafClick={node => this.onNodeSelect(node)} />
    )
    }; 

Please let me know if I am missing anything here.

Thanks,
Farshid

**Comment by helfi92** [comment]
At the moment we only expose 3 properties `value`, `parent` and `id`. I'll see what I can do to have `onLeafClick` display all passed properties.

**Comment by helfi92** [comment]
Published in `v3.3.0`.

**Comment by farshidbakh** [comment]
I upgraded to the latest version , and it works great. Thanks for your quick response. Have a wonderful day!
