### ISSUE TITLE
Material-UI upgrade?

### ISSUE THREAD

**Issue by tregusti** [helfi92/material-ui-treeview#36]
Hi,

I'm looking for a tree component for react and Material UI, and since this seems to be  the only somewhat updated component, I'm wondering about why it's stuck on MUI 1? 3 is out, and 4 around the corner. Normally the major upgrades aren't that hard to handle, at least that is my experience with MUI majors.

I have not tried to run in 3 or 4 yet, but will give it a go.

Will you accept PRs for upgrading to 3?

**Comment by helfi92** [comment]
Hey! Feel free to update the peer-dependency to `^3.0.0`. https://github.com/helfi92/material-ui-treeview/blob/744fb3c69d215ffcdbf12edb371c10f60c049a83/package.json#L59 Thanks @tregusti.

**Comment by tregusti** [comment]
That would result in a major upgrade.

If I decide to continue using this I will do it.

There are some other things I need as well that's missing. Like `onClick` on every node. Investigating the market right now.

**Comment by birendra-90** [comment]
Please update react and react version too.
