### ISSUE TITLE
Contributing to this repository is complicated

### ISSUE THREAD

**Issue by ZakCodes** [helfi92/material-ui-treeview#38]
I've just made a pull request yesterday and when I did it I was worried about forgetting to change something somewhere, and to be honest I'm still not sure that I didn't forget anything.  

I think that there should be a [pull request template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) that would contain a checklist of all the things to make sure you've done when making a modification.

Here's a proposition for the checklist based on what I've had to do for my pull request: 
- [ ] Make sure there are no linter errors (run `yarn lint` to see the errors and `yarn lint --fix` to fix them)
- [ ] Update the example for the component for [Styleguidist](https://react-styleguidist.js.org/) (`src/components/component-name/README.md`)
- [ ] Update the example app (`src/index.jsx`)
- [ ] Update the types and documentation in `README.md`
- [ ] Update the types and documentation in `src/index.d.ts`

I found [this pull request template example](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md) (MIT Licensed) that could be used. However, just having a checklist is probably enough.

**Comment by helfi92** [comment]
This is great. Happy to include a template. The checklist you suggested looks good to me. Feel free to send the PR :)
