### ISSUE TITLE
MUI deprecation warning

### ISSUE THREAD

**Issue by RamilMamedo** [helfi92/material-ui-treeview#44]
https://github.com/helfi92/material-ui-treeview/blob/4a5940460c51a47a3df698fc94e24cd184efea1e/src/components/MuiTreeView/index.jsx#L52

**Material-UI: theme.spacing.unit usage has been deprecated.**
**It will be removed in v5.**
You can replace `theme.spacing.unit * y` with `theme.spacing(y)`.

You can use the `https://github.com/mui-org/material-ui/tree/master/packages/material-ui-codemod/README.md#theme-spacing-api` migration helper to make the process smoother.

**Comment by helfi92** [comment]
Should be fixed in https://github.com/helfi92/material-ui-treeview/issues/36. Looking for someone to help, if you're interested :)
