### ISSUE TITLE
On searching parent node is not unfolding

### ISSUE THREAD

**Issue by nayan826** [helfi92/material-ui-treeview#49]
On searching a child of a tree parent is not unfolding. Can you please look into this why it is `happening.` Below is the `code`

import React,{Component} from 'react';
import './App.css';
import {tree} from './treedata'
import MuiTreeView from 'material-ui-treeview';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { val : "" }
  }
  render() { 

    const handleClick = (event) => {
      this.setState({val : event.target.value})
    }
    console.log(this.state.val)
    return (  
      <div>
        <input onChange={handleClick}></input>
        <MuiTreeView tree = {tree} searchTerm = {this.state.val} softSearch = {tree}/>
        </div>
    );
  }
}
 
export default App;

**Comment by helfi92** [comment]
Are you seeing an error or something? From just looking at the code, I see that there's extra expaces between the "=" symbol as well as an extra `= { tree }` at the end.

Instead of `<MuiTreeView tree = {tree} searchTerm = {this.state.val} softSearch = {tree}/>`, it should probably be `<MuiTreeView tree={tree} searchTerm={this.state.val} softSearch />`.

**Comment by helfi92** [comment]
You can go to https://hassanali.me/material-ui-treeview/ and then click on "View Code" for an example.

**Comment by nayan826** [comment]
I have tried it with spaces removed but still same issue. 
There is no error just parent node is not unfolding. If i search for Child A inside of Parent A then it only shows Parent A instead of Child A underneath Parent A.
![image](https://user-images.githubusercontent.com/11948488/69918846-b0176b80-149c-11ea-912e-836cf432d131.png)

**Comment by helfi92** [comment]
In

```
<MuiTreeView tree = {tree} searchTerm = {this.state.val} softSearch = {tree}/>,
```

```
softSearch = {tree}
```

is definiely wrong since `softSearch` should be a boolean, not a tree:

https://github.com/helfi92/material-ui-treeview/blob/af22545515139706b565bb1b30f7e830bd0972fc/src/components/MuiTreeView/index.jsx#L252

**Comment by nayan826** [comment]
I recognized that should be true and made it true but still nothing changed

<MuiTreeView tree={tree} searchTerm={this.state.val} softSearch={true} />

**Comment by helfi92** [comment]
The next thing to check is the value of `tree`. Can you post the value of that here, please?

**Comment by helfi92** [comment]
What should I be looked at? I don't see anything specific to material-ui-treeview

<img width="1013" alt="Screen Shot 2019-12-01 at 3 01 43 PM" src="https://user-images.githubusercontent.com/3766511/69919516-8a15ab00-144b-11ea-8a87-6e03e4061fde.png">

**Comment by nayan826** [comment]
try again there is unsaved files

**Comment by helfi92** [comment]
Ah, ok I see your issue You can use the `defaultExpanded` prop.

```
<MuiTreeView defaultExpanded ... />
```

**Comment by nayan826** [comment]
But by doing this tree will be opened by default but i want tree to be closed on first render. I don't really want to display whole tree.

**Comment by helfi92** [comment]
I see. I don't think we expose a prop for that. There is however a workaround you can do https://codesandbox.io/s/recursing-lumiere-8dl9g.

**Comment by nayan826** [comment]
This looks great. Thanks
