### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by dimon82** [helfi92/material-ui-treeview#5]
Any way for you to add typings?

**Comment by helfi92** [comment]
I am using https://github.com/facebook/prop-types for prop checking. Does this solve your use case?

https://github.com/helfi92/material-ui-treeview/blob/9f7b35c6cbb4d72fd50489ae69d8fa2605aed268/src/components/MuiTreeView/index.jsx#L58-L79

**Comment by dimon82** [comment]
not really, when I import  `import MuiTreeView from 'material-ui-treeview'`, it gives me TS error saying 

> (TS) Could not find a declaration file for module 'material-ui-treeview'. '...' implicitly has an 'any' type.
  Try `npm install @types/material-ui-treeview` if it exists or add a new declaration (.d.ts) file containing `declare module 'material-ui-treeview';`	

I did add a declaration file to my project to get rid of this error, but it's not type safe, `MuiTreeView` is typed as `any` which is not ideal. I mean I can still use it, but would be good to use typings

**Comment by helfi92** [comment]
I don't have a lot of knowledge with Typescript yet but I would happily accept a PR for it. Let me know if you want to help :)

**Comment by Slessi** [comment]
@helfi92 Yo, small issue

- `import MuiTreeView from 'material-ui-treeview';` is fine
- `import MuiTreeView from 'material-ui-treeview/es5/MuiTreeView';` is not

My project works either way but probably should allow user to use either version - Is the `es5/MuiTreeView` directory created by your `.neutrinorc.js` thing? Could just copy the types file to that directory as well
