### ISSUE TITLE
Write a test for the onEmptySearch prop

### ISSUE THREAD

**Issue by helfi92** [helfi92/material-ui-treeview#51]
Follow up on https://github.com/helfi92/material-ui-treeview/pull/50.

**Comment by ashishzingh** [comment]
will work it as soon as i complete the pending ticket in taskcluster

**Comment by helfi92** [comment]
I just filed https://github.com/taskcluster/taskcluster/issues/2749 to move away from this library and use material-ui's TreeView component instead. This won't be necessary anymore. Let's close this issue :)
